### ISSUE TITLE
Failed to resolve entry for package "bytemd > @types/codemirror"

### ISSUE THREAD

**Issue by benwoodward** [pd4d10/hashmd#121]
When I install `bytemd` with SvelteKit (version: ^1.0.0-next.162), I get the following error:

```
> Failed to resolve entry for package "bytemd > @types/codemirror". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "bytemd > @types/codemirror". The package may have incorrect main/module/exports specified in its package.json.
Error: Failed to resolve entry for package "bytemd > @types/codemirror". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "bytemd > @types/codemirror". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (/Users/ben/dev/my-project/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43739:11)
    at resolvePackageEntry (/Users/ben/dev/my-project/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43735:9)
    at tryNodeResolve (/Users/ben/dev/my-project/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43511:11)
    at Context.resolveId (/Users/ben/dev/my-project/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
    at Object.resolveId (/Users/ben/dev/my-project/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/ben/dev/my-project/node_modules/vite/dist/node/chunks/dep-1be34a63.js:76764:27
    at async optimizeDeps (/Users/ben/dev/my-project/node_modules/vite/dist/node/chunks/dep-1be34a63.js:71535:31)
    at async runOptimize (/Users/ben/dev/my-project/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75389:48)
```

**Comment by AmitPress** [comment]
Yeah Same issue on routify also... I think maybe vite is the reason cause vite is the common factor in both kit and routify

**Comment by pd4d10** [comment]
Thanks for the feedback! Provided an example [here](https://github.com/bytedance/bytemd/tree/main/examples/svelte-kit)

Looks similar to #96, let's track SvelteKit/Vite related issues there.
