### ISSUE TITLE
Svelte Rollup error

### ISSUE THREAD

**Issue by wktdev** [pd4d10/hashmd#17]
I installed Bytemd and when I try to run the example code ( for Svelte) I get a dependency error.
I have not tried to install the dependency yet, but the fact that this is not mentioned in the installation  instructions is something that I thought you might like to take note of.

```
Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@bytemd/plugin-gfm (imported by src/views/WorkflowEdit.svelte)
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/hast-util-sanitize/lib/github.json (2:9)
1: {
2:   "strip": [
            ^
3:     "script"
4:   ],
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (/home/wktdev/Desktop/svelte_workflow_magic_v2/app/node_modules/rollup/dist/shared/rollup.js:5265:30)
    at Module.error (/home/wktdev/Desktop/svelte_workflow_magic_v2/app/node_modules/rollup/dist/shared/rollup.js:9835:16)
    at tryParse (/home/wktdev/Desktop/svelte_workflow_magic_v2/app/node_modules/rollup/dist/shared/rollup.js:9716:23)
    at Module.setSource (/home/wktdev/Desktop/svelte_workflow_magic_v2/app/node_modules/rollup/dist/shared/rollup.js:10142:19)
    at ModuleLoader.addModuleSource (/home/wktdev/Desktop/svelte_workflow_magic_v2/app/node_modules/rollup/dist/shared/rollup.js:18312:20)

```

Okay, I tried to install the plug in and it devolved into a little mess but I eventually fixed it.
I went to install the plug in here:
https://www.npmjs.com/package/@rollup/plugin-json

I had to go to rollup.config and update the file to look like this:
...
```
export default {
	input: 'src/main.js',
	output: {

		sourcemap: true,
	    dir:"output",
		format: 'cjs',
		name: 'app',
		//file: 'public/build/bundle.js'
	},

	plugins: [
	    json(),
	
           .... ]
```
          

Oops, spoke too soon!

The errors are gone but the plug in doesn't actually display/work!

I reverted back to my old rollup.config. I have pasted it below in case you know how to edit it properly.
Thanks!

```
import svelte from 'rollup-plugin-svelte';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import css from 'rollup-plugin-css-only';

const production = !process.env.ROLLUP_WATCH;

function serve() {
	let server;

	function toExit() {
		if (server) server.kill(0);
	}

	return {
		writeBundle() {
			if (server) return;
			server = require('child_process').spawn('npm', ['run', 'start'], {
				stdio: ['ignore', 'inherit', 'inherit'],
				shell: true
			});

			process.on('SIGTERM', toExit);
			process.on('exit', toExit);
		}
	};
}

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		svelte({
			compilerOptions: {
				// enable run-time checks when not in production
				dev: !production
			}
		}),
		// we'll extract any component CSS out into
		// a separate file - better for performance
		css({ output: 'bundle.css' }),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration -
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
		commonjs(),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};
```

**Comment by pd4d10** [comment]
Hi, @wktdev , thanks for your feedback!

It seems related to #6 . Will update the rollup example soon.

**Comment by pd4d10** [comment]
See https://github.com/bytedance/bytemd/tree/main/examples/svelte-rollup

**Comment by wktdev** [comment]
I don't understand what any of this means.

Set output.inlineDynamicImports to true

Where is that?????


Replace rollup-plugin-css-only with rollup-plugin-postcss to import CSS files correctly

huh???

Add @rollup/plugin-json for JSON file imports

how do I do that?

Add @rollup/plugin-replace for process.env.NODE_ENV value

What?

**Comment by pd4d10** [comment]
> With some tweaks based upon svelte-rollup-template:

It is modified based on [svelte-rollup-template](https://github.com/sveltejs/template)

If your project isn't initialized from this template, just refer to the [rollup config](https://github.com/bytedance/bytemd/blob/main/examples/svelte-rollup/rollup.config.js)
