### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Folyd** [pd4d10/hashmd#260]
Here is the error log:
```
codemirror.js:677 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at splitLinesAuto (codemirror.js:677:41)
    at Doc.splitLines (codemirror.js:6510:14)
    at Doc.<anonymous> (codemirror.js:6163:36)
    at Doc.setValue (codemirror.js:3977:22)
    at CodeMirror.setValue (codemirror.js:9808:40)
    at $$self.$$.update (editor.svelte:110:12)
    at update (index.mjs:1205:12)
    at flush (index.mjs:1169:17)
```

```json
"dependencies": {
    "bytemd": "^1.20.0",
},
```

**Comment by pd4d10** [comment]
Could you please provide a minimal reproduction?
